on: [push]
name: "CI"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn
      - run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: c-hive/gha-yarn-cache@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install &> /dev/null
      - run: yarn test
    env:
      CI: true
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn
      - run: yarn build:ci:clean
      - run: yarn build:ci
